import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import Ajv from 'ajv'
import standaloneCode from 'ajv/dist/standalone/index.js'

import {
  alternativeSchema,
  automatedAssessmentSchema,
  caseSchema,
  legacyArtifactSchema,
  projectSchema,
  runManifestSchema,
  runSchema,
  scenarioSchema,
} from '../src/schemas.js'

const schemas = {
  validateProject: projectSchema,
  validateAlternative: alternativeSchema,
  validateCase: caseSchema,
  validateScenario: scenarioSchema,
  validateRunManifest: runManifestSchema,
  validateAutomatedAssessment: automatedAssessmentSchema,
  validateRun: runSchema,
  validateLegacyArtifact: legacyArtifactSchema,
}

const targetDirectory = path.resolve(import.meta.dirname, '../src/generated')
await mkdir(targetDirectory, { recursive: true })
for (const [name, schema] of Object.entries(schemas)) {
  const ajv = new Ajv({ allErrors: true, strict: true, validateFormats: false, code: { source: true, esm: true } })
  const validate = ajv.compile(schema)
  await writeFile(
    path.join(targetDirectory, `${name}.ts`),
    `// Generated by scripts/generate-validators.ts. Do not edit.\n// @ts-nocheck\n${standaloneCode(ajv, validate)}\n`,
  )
}

const exports = Object.keys(schemas).map((name) => `export { default as ${name} } from './${name}.js'`).join('\n')
await writeFile(path.join(targetDirectory, 'validators.ts'), `// Generated validator exports. Do not edit.\n${exports}\n`)
