"""open_waterhammer — 農業用パイプライン水撃圧計算コア (Python).

土地改良設計基準 設計「パイプライン」技術書（令和3年6月改訂）を参照した
水理計算の Python 実装。本パッケージが計算ロジックの単一の真理源であり、
ブラウザアプリは Pyodide 経由でこの同じコードを呼び出す。

License: AGPL-3.0-or-later
"""

from .moc import (
    MOC_GRID_SPACING_MAX,
    MOC_GRID_SPACING_RECOMMENDED_MIN,
    MOC_VAPOR_PRESSURE_HEAD,
    AirChamberBC,
    AirReleaseValveBC,
    BoundaryCondition,
    DeadEndBC,
    MocNetwork,
    MocNodeResult,
    MocOptions,
    MocPipeResult,
    MocPipeSegment,
    MocResult,
    MocSnapshot,
    PressureReducingValveBC,
    PumpBC,
    PumpStartInput,
    PumpTripInput,
    ReachCandidatePipe,
    ReservoirBC,
    SinglePipeMocInput,
    SuggestReachesResult,
    SurgeTankBC,
    ValveBC,
    harmonize_time_step,
    run_moc,
    run_moc_pump_start,
    run_moc_pump_trip,
    run_moc_single_pipe,
    suggest_reaches,
)
from .formulas import (
    BULK_MODULUS_WATER,
    GRAVITY,
    WATER_UNIT_WEIGHT,
    allievi_close,
    allievi_open,
    calc_allievi_k1,
    calc_design_pressure,
    calc_empirical_waterhammer,
    calc_equivalent_length,
    calc_vibration_period,
    calc_wave_speed,
    calc_wave_speed_result,
    determine_closure_type,
    head_to_mpa,
    joukowsky,
    judge_design_pressure,
    mpa_to_head,
)
from .longitudinal_hydraulic import (
    calc_longitudinal_hydraulic,
    calc_minor_loss,
    calc_segment_friction,
    calc_total_loss_coeff,
)
from .pipe_materials import PIPE_MATERIALS, PipeMaterial, get_long_term_youngs_modulus
from .simple_calculation import run_simple_formula
from .steady_flow import (
    SteadyFlowResult,
    calc_darcy_weisbach,
    calc_hazen_williams,
)
from .steady_network import (
    NetworkNodeDef,
    NetworkNodeResult,
    NetworkPipeDef,
    NetworkPipeResult,
    SteadyNetworkInput,
    SteadyNetworkResult,
    calc_steady_network,
)
from .steady_to_moc import (
    PipeMaterialSpec,
    SteadyToMocInput,
    SteadyToMocOutput,
    SteadyToMocSummary,
    build_moc_from_steady,
    build_pump_upstream_bc,
)
from .types import (
    CalculationCase,
    ClosureDetermination,
    ClosureType,
    EmpiricalWaterhammerResult,
    JudgementResult,
    JudgementStatus,
    LongitudinalHydraulicInput,
    LongitudinalHydraulicResult,
    MeasurementPoint,
    MeasurementPointResult,
    OperationType,
    Pipe,
    PipelineSystemType,
    PipeType,
    SimpleFormulaResult,
    WaveSpeedResult,
)

__version__ = "0.1.0"

__all__ = [
    # constants
    "GRAVITY",
    "BULK_MODULUS_WATER",
    "WATER_UNIT_WEIGHT",
    # functions
    "calc_wave_speed",
    "calc_vibration_period",
    "determine_closure_type",
    "calc_wave_speed_result",
    "joukowsky",
    "calc_allievi_k1",
    "allievi_close",
    "allievi_open",
    "calc_equivalent_length",
    "calc_design_pressure",
    "judge_design_pressure",
    "calc_empirical_waterhammer",
    "head_to_mpa",
    "mpa_to_head",
    # pipe materials
    "PIPE_MATERIALS",
    "PipeMaterial",
    "get_long_term_youngs_modulus",
    # types
    "Pipe",
    "PipeType",
    "ClosureType",
    "ClosureDetermination",
    "WaveSpeedResult",
    "PipelineSystemType",
    "EmpiricalWaterhammerResult",
    "JudgementStatus",
    "JudgementResult",
    # MOC
    "MOC_GRID_SPACING_RECOMMENDED_MIN",
    "MOC_GRID_SPACING_MAX",
    "MOC_VAPOR_PRESSURE_HEAD",
    "BoundaryCondition",
    "ReservoirBC",
    "ValveBC",
    "PumpBC",
    "AirChamberBC",
    "SurgeTankBC",
    "AirReleaseValveBC",
    "PressureReducingValveBC",
    "DeadEndBC",
    "MocPipeSegment",
    "MocNetwork",
    "MocOptions",
    "MocSnapshot",
    "MocPipeResult",
    "MocNodeResult",
    "MocResult",
    "SinglePipeMocInput",
    "PumpTripInput",
    "PumpStartInput",
    "ReachCandidatePipe",
    "SuggestReachesResult",
    "harmonize_time_step",
    "suggest_reaches",
    "run_moc",
    "run_moc_single_pipe",
    "run_moc_pump_trip",
    "run_moc_pump_start",
    # simple-calculation
    "run_simple_formula",
    # steady-flow（単管路）
    "calc_darcy_weisbach",
    "calc_hazen_williams",
    # steady-network
    "NetworkPipeDef",
    "NetworkNodeDef",
    "SteadyNetworkInput",
    "NetworkPipeResult",
    "NetworkNodeResult",
    "SteadyNetworkResult",
    "calc_steady_network",
    "SteadyFlowResult",
    # longitudinal-hydraulic
    "calc_total_loss_coeff",
    "calc_minor_loss",
    "calc_segment_friction",
    "calc_longitudinal_hydraulic",
    # steady-to-moc
    "PipeMaterialSpec",
    "SteadyToMocInput",
    "SteadyToMocSummary",
    "SteadyToMocOutput",
    "build_moc_from_steady",
    "build_pump_upstream_bc",
    # additional types
    "CalculationCase",
    "OperationType",
    "MeasurementPoint",
    "MeasurementPointResult",
    "LongitudinalHydraulicInput",
    "LongitudinalHydraulicResult",
    "SimpleFormulaResult",
]
